[package]
name = "hark"
version = "0.1.0"
authors = ["Eric Mikulin <ericm99@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
config = {"version"="0.9", "features"=["json"]}
log = "0.4"
reqwest = {"version"="0.11", "features"=["blocking", "json"]}
simplelog = "0.9"
procfs = "0.9"
